public class mapSolve {
    
    public static void map1(){
    List<String> ls = new List<String>{'Rahul sir','Lokesh sir'};
        List<String> ls1 = new List<String>{'Rachit sir','Nilesh sir','Surendra Sir'};
            Map<String,list<String>> record = new Map<string,list<String>>();
            record.put('Director',ls);
            record.put('Developer',ls1);
                system.debug(record);
        
    
}
}